function T=captureDowntownFineReference()
% captureDowntownFineReference: Freeze original fine points on Downtown frames.
% Keep every default Downtown semantic channel: facade processing can affect
% independent fine pole candidates. No fine threshold or label is adjusted.
% Checkpoint each completed frame; resume matching partial captures and leave
% complete frozen references unchanged.
    root=setupVehicleLocalization();folder=fileparts(mfilename('fullpath'));
    output=fullfile(root,'output','pillar_fine_alignment_20260926');
    if ~isfolder(output),mkdir(output);end
    destination=fullfile(output,'downtown_reference.mat');
    csvPath=fullfile(folder,'baseline_downtown_frames.csv');
    frames=round(linspace(1,539,24));dataset="Downtown";
    frozenRevision='35cdb88388300ba1b8bb215905435bde670dff03';
    % Reuse already frozen identities before comparing the current coarse
    % implementation with the historical generator. Never regenerate labels
    % merely because the detector under evaluation has changed.
    if isfile(destination)
        frozen=load(destination,'complete','processed','frames','metadata','T');
        if frozen.complete
            assert(isequal(frozen.frames,frames) && frozen.processed==numel(frames) && ...
                strcmp(frozen.metadata.fineSourceRevision,frozenRevision));
            T=frozen.T;return;
        end
    end
    checkedSources=confirmFineSources(root,frozenRevision);
    fineCfg=perceptionConfig(dataset,"offline");coarseCfg=perceptionConfig(dataset);
    assert(isequal(fineCfg.voxel.voxelSize,[.3 .3]) && ...
        fineCfg.executionMode=="offline" && fineCfg.offGroundFeatures.pole.detector=="pillar", ...
        'The reference must use the unchanged offline 0.3 m pillar branch.');
    assert(isequal(sort(string(fineCfg.featureNames(:))), ...
        sort(["curb";"pole";"facade";"trafficSign"])), ...
        'Preserve all four default Downtown fine semantic channels.');
    assert(isequal(coarseCfg.voxel.voxelSize,[.6 .6]) && ...
        coarseCfg.offGroundFeatures.pole.detector=="shaft" && ...
        coarseCfg.offGroundFeatures.pole.probabilityEvidence=="shaft", ...
        'The baseline must use the current 0.6 m coarse shaft configuration.');
    previous=load(fullfile(root,'output','pillar_shaft_20260926','downtown_pipeline.mat'), ...
        'frames','records','g');
    assert(isequal(double(previous.frames(:).'),frames), ...
        'The prior Downtown reference uses different frames.');
    references=cell(numel(frames),1);rows=references;processed=0;complete=false;
    metadata=struct('dataset',dataset,'sourceRecording','data/raw/downTownPointClouds.mat', ...
        'fineSourceRevision',frozenRevision,'checkedFineSources',{checkedSources}, ...
        'referenceKind','Original point indices and XYZ from unchanged offline 0.3 m fine masks', ...
        'pointCoordinates','Original stored raw frame XYZ, without Gaussian calibration or projection', ...
        'priorReference','output/pillar_shaft_20260926/downtown_pipeline.mat', ...
        'featureChannels','All default Downtown channels retained', ...
        'status','partial','recordedAtUtc',utcNow());
    geometry=previous.g;
    if isfile(destination)
        saved=load(destination);
        assert(isequal(saved.frames,frames) && isequaln(saved.fineCfg,fineCfg) && ...
            isequaln(saved.coarseCfg,coarseCfg), ...
            'Existing Downtown capture differs; preserve it instead of overwriting references.');
        assert(saved.processed>=0 && saved.processed<=numel(frames) && ...
            saved.processed==floor(saved.processed),'Invalid partial-capture progress.');
        if saved.complete
            assert(saved.processed==numel(frames),'A complete capture must include every requested frame.');
            T=saved.T;
            fprintf('Reusing complete frozen Downtown fine reference (%d frames).\n',height(T));
            return;
        end
        references=saved.references;rows=saved.rows;processed=saved.processed;metadata=saved.metadata;
    end
    source=matfile(fullfile(root,'data','raw','downTownPointClouds.mat'));
    for k=processed+1:numel(frames)
        frame=source.pointClouds(1,frames(k));
        timer=tic;fine=perceiveFrame(frame,fineCfg);fineMilliseconds=1000*toc(timer);
        assert(fine.executionMode=="offline" && isfield(fine,'featureMasks'));
        finePointIndices=find(fine.featureMasks.pole);
        timer=tic;coarse=perceiveFrame(frame,coarseCfg);coarseMilliseconds=1000*toc(timer);
        ids=double(coarse.candidates.pillarIndices{coarse.candidates.semanticNames=="pole"});
        assert(isequal(coarse.candidates.geometry,geometry), ...
            'The coarse geometry differs from the prior frozen capture.');
        [metrics,detail]=measureFinePoleAlignment(frame,finePointIndices,ids,geometry);
        old=previous.records{k};
        assert(isequal(detail.finePillarIds,double(old.fineCells(:))), ...
            'Recreated fine pillar IDs differ from the original Downtown reference.');
        assert(isequal(ids,double(old.poleCells(:))), ...
            'Current coarse baseline candidates differ from the original shaft capture.');
        assert(isequaln(coarse.probabilityCloud.components,old.components) && ...
            isequaln(coarse.sourceSummary,old.sourceSummary), ...
            'Current coarse baseline Gaussian output or source summary changed.');
        xyz=double([frame.x(:),frame.y(:),frame.z(:)]);
        references{k}=struct('frame',frames(k),'pointIndices',finePointIndices, ...
            'points',xyz(finePointIndices,:),'pointPillarIds',detail.finePointPillarIds, ...
            'finePillarIds',detail.finePillarIds,'geometry',geometry, ...
            'baselinePoleCells',ids,'baselineCandidates',coarse.candidates, ...
            'baselineComponents',coarse.probabilityCloud.components, ...
            'baselineSourceSummary',coarse.sourceSummary);
        row=struct('frame',frames(k),'fineMilliseconds',fineMilliseconds, ...
            'coarseMilliseconds',coarseMilliseconds,'finePillarsMatchPrevious',true, ...
            'coarseOutputMatchesPrevious',true);
        for name=fieldnames(metrics).',row.(name{1})=metrics.(name{1});end
        rows{k}=row;processed=k;complete=k==numel(frames);
        metadata.status='partial';if complete,metadata.status='complete';end
        metadata.recordedAtUtc=utcNow();
        T=struct2table(vertcat(rows{1:processed}));
        temporary=fullfile(output,'downtown_reference_partial_write.mat');
        save(temporary,'dataset','frames','fineCfg','coarseCfg','references','rows','T', ...
            'geometry','metadata','processed','complete','-v7.3');
        [ok,message]=movefile(temporary,destination,'f');
        assert(ok,'Could not checkpoint Downtown reference: %s',message);
        writetable(T,csvPath);
        fprintf('Frozen Downtown reference %d/%d, frame %d, fine %.1f ms, coarse %.1f ms\n', ...
            k,numel(frames),frames(k),fineMilliseconds,coarseMilliseconds);
    end
end

function sources=confirmFineSources(root,revision)
    sources={
        'config/perceptionConfig.m','config/finePerceptionConfig.m', ...
        'config/fineStructuralConfig.m','config/pillarGridConfig.m', ...
        'config/groundSegmentationConfig.m','config/groundFeatureConfig.m', ...
        'config/structuralPillarConfig.m','perception/perceiveFrame.m', ...
        'perception/pillarizePointCloud.m','perception/refinePerceptionCandidates.m', ...
        'perception/groundSegmentation/segmentGround.m', ...
        'perception/offGroundFeatures/analyzeFineStructuralCandidates.m', ...
        'perception/offGroundFeatures/detectPoleCandidates.m', ...
        'perception/offGroundFeatures/retainContinuousPoleSupport.m', ...
        'perception/offGroundFeatures/completeRecoveredPoleShafts.m', ...
        'perception/offGroundFeatures/validatePoleIsolation.m'};
    originalDirectory=pwd;cleanup=onCleanup(@()cd(originalDirectory)); %#ok<NASGU>
    cd(root);
    % Revision and paths are fixed trusted literals, not user input.
    [status,changed]=system(['git --no-pager diff --name-only ' revision ' -- ' strjoin(sources,' ')]);
    assert(status==0 && isempty(strtrim(changed)), ...
        'Fine reference source/configuration changed relative to %s: %s',revision,changed);
    assert(all(cellfun(@(name)isfile(fullfile(root,name)),sources)), ...
        'A required original fine source file is missing.');
end

function value=utcNow()
    value=char(datetime('now','TimeZone','UTC','Format',"yyyy-MM-dd'T'HH:mm:ss'Z'"));
end
