function [metrics,detail] = measureFinePoleAlignment(frame,finePointIndices,candidatePillarIds,geometry,eligiblePointIndices)
% measureFinePoleAlignment: Score coarse pillars against frozen fine points.
% Fine indices address original frame points. Project their original XY into
% the published coarse geometry; never infer targets from old coarse labels.
% Only the finite XY region of interest limits the primary denominator.
% Optional retained-point indices diagnose filtering without changing targets.
% Reference-empty cells are detector disagreements, not confirmed physical
% false detections: the original fine detector can miss real features.
    count=numel(frame.x);
    assert(numel(frame.y)==count,'Frame coordinate arrays must have equal lengths.');
    if islogical(finePointIndices)
        assert(numel(finePointIndices)==count,'A fine mask must address the original frame.');
        finePointIndices=find(finePointIndices);
    end
    finePointIndices=double(finePointIndices(:));
    assert(all(isfinite(finePointIndices) & finePointIndices==floor(finePointIndices) & ...
        finePointIndices>=1 & finePointIndices<=count), ...
        'Fine indices must address valid original frame points.');
    assert(numel(unique(finePointIndices))==numel(finePointIndices), ...
        'Fine point indices must not contain duplicates.');
    origin=double(geometry.origin(:).'); spacing=double(geometry.cellSize(:).');
    dims=double(geometry.mapSize(:).');
    assert(numel(origin)==2 && numel(spacing)==2 && numel(dims)==2 && ...
        all(isfinite([origin spacing dims])) && all(spacing>0) && ...
        all(dims>=1 & dims==floor(dims)),'Invalid coarse pillar geometry.');
    candidatePillarIds=unique(double(candidatePillarIds(:)));
    assert(all(isfinite(candidatePillarIds) & candidatePillarIds==floor(candidatePillarIds) & ...
        candidatePillarIds>=1 & candidatePillarIds<=prod(dims)), ...
        'Candidate IDs must belong to the published coarse geometry.');
    x=double(frame.x(:)); y=double(frame.y(:));
    xy=[x(finePointIndices),y(finePointIndices)];
    bins=floor((xy-origin)./spacing)+1;
    valid=all(isfinite(xy),2) & all(bins>=1 & bins<=[dims(2) dims(1)],2);
    pointPillarIds=zeros(numel(finePointIndices),1);
    pointPillarIds(valid)=sub2ind(dims,bins(valid,2),bins(valid,1));
    finePillarIds=unique(pointPillarIds(valid));
    covered=valid & ismember(pointPillarIds,candidatePillarIds);
    coveredPillars=intersect(candidatePillarIds,finePillarIds);
    extraPillars=setdiff(candidatePillarIds,finePillarIds);
    metrics=struct('finePointCount',numel(finePointIndices), ...
        'finePointCountInRoi',nnz(valid),'finePointCountOutsideRoi',nnz(~valid), ...
        'coveredFinePointCount',nnz(covered),'pointCoverage',ratio(nnz(covered),nnz(valid)), ...
        'pointCoverageAllFine',ratio(nnz(covered),numel(finePointIndices)), ...
        'finePillarCount',numel(finePillarIds),'coveredFinePillarCount',numel(coveredPillars), ...
        'pillarRecall',ratio(numel(coveredPillars),numel(finePillarIds)), ...
        'candidatePillarCount',numel(candidatePillarIds),'extraPillarCount',numel(extraPillars), ...
        'extraPillarFraction',ratio(numel(extraPillars),numel(candidatePillarIds)), ...
        'pillarPrecision',ratio(numel(coveredPillars),numel(candidatePillarIds)), ...
        'pillarJaccard',ratio(numel(coveredPillars),numel(union(candidatePillarIds,finePillarIds))), ...
        'eligibleFinePointCount',NaN,'coveredEligibleFinePointCount',NaN);
    eligible=false(numel(finePointIndices),1);
    if nargin>=5
        if islogical(eligiblePointIndices)
            assert(numel(eligiblePointIndices)==count,'An eligibility mask must address the original frame.');
            eligiblePointIndices=find(eligiblePointIndices);
        end
        eligiblePointIndices=double(eligiblePointIndices(:));
        assert(all(isfinite(eligiblePointIndices) & eligiblePointIndices==floor(eligiblePointIndices) & ...
            eligiblePointIndices>=1 & eligiblePointIndices<=count),'Invalid retained-point indices.');
        eligible=valid & ismember(finePointIndices,eligiblePointIndices);
        metrics.eligibleFinePointCount=nnz(eligible);
        metrics.coveredEligibleFinePointCount=nnz(covered & eligible);
    end
    detail=struct('finePointIndices',finePointIndices,'finePointPillarIds',pointPillarIds, ...
        'finePointInRoi',valid,'finePointCovered',covered,'finePointEligible',eligible, ...
        'finePillarIds',finePillarIds,'coveredFinePillarIds',coveredPillars, ...
        'missedFinePillarIds',setdiff(finePillarIds,candidatePillarIds), ...
        'extraPillarIds',extraPillars);
end

function value=ratio(numerator,denominator)
    if denominator==0, value=NaN; else, value=numerator/denominator; end
end
