function assertSensorOnlyLidarTilt(tilt)
% assertSensorOnlyLidarTilt Reject legacy caches carrying reference-derived tilt.
    assert(isstruct(tilt) && all(isfield(tilt, ...
        {'schemaVersion','source','referencePoseUsed','causal','configuration'})) && ...
        tilt.schemaVersion==1 && ~tilt.referencePoseUsed && tilt.causal && ...
        ismember(string(tilt.source),["front-ouster-raw-imu","disabled"]), ...
        'VehicleLocalization:ReferenceTiltCache','Regenerate source inputs using sensor-only tilt; legacy reference-attitude caches are not allowed.');
end
