function design=designFullObserverGains(cfg)
% designFullObserverGains Certify continuous gains before discretization.
% One design route applies independently of the measurement timing interface.
% The continuous seven-state ISS LMIs include position/heading coupling and
% motion-output feedback. Numerical integration uses these gains unchanged.
    arguments
        cfg (1,1) struct=fullObserverConfig()
    end
    obsolete=intersect(string(fieldnames(cfg.gnss)).',["headingGain","courseWindow", ...
        "maximumCourseGap","minimumCourseDisplacement","minimumSpeed","headingErrorLimit"]);
    assert(isempty(obsolete),'VehicleLocalization:ObsoleteFullConfig', ...
        'GNSS does not correct the heading; remove cfg.gnss fields: %s.',strjoin(obsolete,', '));
    certificate=solveFullObserverIssLmi(cfg);
    assert(certificate.certified,'VehicleLocalization:InfeasibleFullCertificate', ...
        'Candidate gains failed the continuous seven-state ISS LMIs: %s',certificate.solverInfo);
    g=cfg.gains(:);
    validateattributes(cfg.gnss.minimumPositionWeight,{'numeric'},{'real','finite','>',0,'<=',1,'scalar'});
    % Retain the old GNSS-only conditional diagnostic, not a gain-design gate.
    alpha=cfg.gnss.positionGain*cfg.gnss.minimumPositionWeight;
    matrices=zeros(3,3,2);margins=zeros(2,1);
    for k=1:2
        q2=(k-1)*cfg.maximumTrackAngleRate^2;
        matrices(:,:,k)=[2*alpha,-1,0;-1,2*g(2),-(1+q2);0,-(1+q2),2*g(3)];
        margins(k)=min(eig(matrices(:,:,k)));
    end
    matched=struct('P',blkdiag(eye(6),g(1)/g(4)),'T',eye(7),'theta',1, ...
        'scalingExponents',[1;2;3;1;2;3;1],'kappa',g(1), ...
        'baselineFullStateCertified',false, ...
        'metricSource',"Algebraic LiDAR injection metric; the full continuous proof uses continuousCertificate.verification.P");
    design=struct('kind',cfg.kind,'gains',g.','gnssPositionGain',cfg.gnss.positionGain, ...
        'translationP',eye(6),'comparisonMatrices',matrices, ...
        'translationMargins',margins,'commonTranslationMargin',min(margins), ...
        'matrixCertificateVerified',true,'unconditionalIssClaimed',false, ...
        'baselineFullStateCertified',false,'lidarMatched',matched, ...
        'continuousCertificate',certificate,'fullContinuousStateCertified',true, ...
        'designRoute',certificate.designRoute, ...
        'scope',certificate.verification.scope);
end
