function design=designMotionAidedObserverGains(cfg)
% designMotionAidedObserverGains Certify physical pose and motion gains.
% For the error coordinates [ep,ev,ea], P=I gives a dissipation lower bound
% M=[2*kp*w,-1,0;-1,2*kv,-(1+q^2);0,-(1+q^2),2*ka].
% M is affine in q^2; checking 0 and qMax^2 covers arbitrary time variation.
% The skew 2*q*J term cancels. Heading is a preceding scalar stable system.
% This certificate is specific to the new output structure, not the old LMI.
    arguments
        cfg (1,1) struct=motionAidedObserverConfig()
    end
    g=cfg.gains;
    assert(isnumeric(g) && isreal(g) && numel(g)==4 && all(isfinite(g)) ...
        && all(g>0),'VehicleLocalization:InvalidMotionGains','Four positive physical gains are required.');
    assert(isscalar(cfg.maximumTrackAngleRate) && isfinite(cfg.maximumTrackAngleRate) ...
        && cfg.maximumTrackAngleRate>=0 && isequal(cfg.lidar.poseScales(:),ones(3,1)) ...
        && isscalar(cfg.lidar.minimumPoseWeight) && isfinite(cfg.lidar.minimumPoseWeight) ...
        && cfg.lidar.minimumPoseWeight>0 && cfg.lidar.minimumPoseWeight<=1, ...
        'VehicleLocalization:InvalidMotionConfiguration','Invalid rate bound or physical pose weighting.');
    w=cfg.lidar.minimumPoseWeight;q2=[0,cfg.maximumTrackAngleRate^2];
    matrices=zeros(3,3,2);margins=zeros(2,1);
    for k=1:2
        matrices(:,:,k)=[2*g(1)*w,-1,0;-1,2*g(2),-(1+q2(k));0,-(1+q2(k)),2*g(3)];
        margins(k)=min(eig(matrices(:,:,k)));
    end
    margin=min(margins);
    assert(margin>1e-9,'VehicleLocalization:InfeasibleMotionCertificate', ...
        'The structured common quadratic certificate is not positive definite.');
    design=struct('kind',cfg.kind,'gains',g(:).','certificateVerified',true, ...
        'translationP',eye(6),'comparisonMatrices',matrices, ...
        'translationDissipationMargin',margin,'translationDecayRate',margin/2, ...
        'headingDecayRate',g(4)*w,'maximumTrackAngleRate',cfg.maximumTrackAngleRate, ...
        'minimumPoseWeight',w,'scope', ...
        "Conditional ISS for a zero-delay lifted-heading cascade with bounded sensor/model disturbances; no RMSE dominance theorem.");
end
