function problem=fullObserverIssProblem(cfg)
% fullObserverIssProblem Declare the continuous seven-state ISS assumptions.
% A fixed candidate gain makes the two comparison inequalities LMIs in the
% Lyapunov weights. Timing and integration method do not enter this problem.
    arguments
        cfg (1,1) struct
    end
    assert(isfield(cfg,'iss'),'VehicleLocalization:MissingFullIssDomain', ...
        'Declare the continuous ISS domain in cfg.iss before selecting gains.');
    s=cfg.iss;g=cfg.gains(:).';
    validateattributes(g,{'numeric'},{'real','finite','positive','numel',4});
    validateattributes(cfg.maximumTrackAngleRate,{'numeric'},{'real','finite','nonnegative','scalar'});
    validateattributes(cfg.gnss.positionGain,{'numeric'},{'real','finite','nonnegative','scalar'});
    scale=cfg.gnss.gainInformationScale;
    assert(isnumeric(scale) && isscalar(scale) && isreal(scale) && isfinite(scale) && scale>0, ...
        'VehicleLocalization:InvalidGnssInformationScale', ...
        'A positive GNSS regularizer is required for the certified weight bound.');
    validateattributes([s.maximumSpeed,s.maximumAcceleration,s.maximumPositionHeadingCoupling], ...
        {'numeric'},{'real','finite','nonnegative','numel',3});
    validateattributes([s.minimumPositionStrength,s.minimumHeadingStrength], ...
        {'numeric'},{'real','finite','positive','<',1,'numel',2});
    validateattributes([s.decayRate,s.tolerance],{'numeric'},{'real','finite','positive','numel',2});
    assert(isequal(cfg.lidar.poseScales(:),ones(3,1)), ...
        'VehicleLocalization:UnsupportedFullIssScaling','The continuous comparison uses metres and radians without pose rescaling.');
    filterLidarPoseInformation(zeros(3),cfg);
    offset=zeros(2,1);
    if isfield(cfg.gnss,'outputPoint'),offset=cfg.gnss.outputPoint.bodyOffset(:);end
    validateattributes(offset,{'numeric'},{'real','finite','numel',2});
    problem=struct('gains',g,'maximumCourseRate',cfg.maximumTrackAngleRate, ...
        'maximumSpeed',s.maximumSpeed,'maximumAcceleration',s.maximumAcceleration, ...
        'minimumPositionStrength',s.minimumPositionStrength, ...
        'minimumHeadingStrength',s.minimumHeadingStrength, ...
        'maximumPositionHeadingCoupling',s.maximumPositionHeadingCoupling, ...
        'decayRate',s.decayRate,'gnssLeverPenalty',.5*cfg.gnss.positionGain*sum(offset.^2), ...
        'gnssPositionGain',cfg.gnss.positionGain,'gnssBodyOffset',offset, ...
        'lidarInformationScale',cfg.lidar.gainInformationScale, ...
        'gnssInformationScale',cfg.gnss.gainInformationScale, ...
        'tolerance',s.tolerance);
end
