function design = improvedObserverReferenceDesign(cfg)
% improvedObserverReferenceDesign Load gains and verify their reference model.
% Certification concerns the historical current-pose pulse equations only.
% The fixed-delay transport runtime exposes this provenance separately.
    arguments
        cfg (1,1) struct = improvedObserverConfig()
    end
    root = fileparts(fileparts(mfilename('fullpath')));
    data = jsondecode(fileread(fullfile(root,'config','poseObserverCertificate.json')));
    design = struct('kind',string(data.kind),'K',data.K,'N',data.N, ...
        'P',data.timer.P(:,:,1),'theta',data.theta,'sigma',data.theta, ...
        'scalingExponents',data.scalingExponents,'timer',data.timer, ...
        'knownInputIncludedExactly',true,'cfg',cfg);
    assert(cfg.observer.theta==data.theta && cfg.observer.sigma==data.theta, ...
        'VehicleLocalization:CertificateMismatch','The stored design requires theta=sigma=3.5.');
    assert(cfg.operating.maximumSpeed<=data.operating.maximumSpeed ...
        && cfg.operating.maximumAcceleration<=data.operating.maximumAcceleration ...
        && cfg.operating.maximumTrackAngleRate<=data.operating.maximumTrackAngleRate ...
        && isequal(cfg.lidar.poseScales(:),data.timer.poseScales(:)), ...
        'VehicleLocalization:CertificateMismatch','The requested envelope exceeds the stored certificate.');
    design.verification = verifyImprovedObserverDesign(design,cfg);
    design.certified = design.verification.certified;
    assert(design.certified,'VehicleLocalization:CertificateMismatch', ...
        'The stored pulse observer failed exhaustive verification.');
end
