function conditions = observerCertificateConditions(highRate,gps,lidar,acceptedGps,acceptedLidar,onlineState,cfg)
% observerCertificateConditions Report observable hypotheses, not a theorem flag.
% Qualified-pose gaps are measured at sensor timestamps. Arrival delay is
% checked separately, so a stale delivery cannot masquerade as a fresh pose.
    time = highRate.time;
    stamps = sort(lidar.timestamp(acceptedLidar));
    gaps = diff(stamps);
    if isempty(gaps), largestGap = Inf; else, largestGap = max(gaps); end
    fresh = false(size(time));
    for k=1:numel(stamps)
        fresh = fresh | (time>=stamps(k) & time<=stamps(k)+cfg.measurement.maximumPoseInterval);
    end
    delay = lidar.arrivalTime(acceptedLidar)-lidar.timestamp(acceptedLidar);
    if isempty(delay), delayMatches=false; else
        delayMatches=all(abs(delay-cfg.measurement.fixedLidarDelay)<1e-8);
    end
    tooShort = gaps<cfg.measurement.minimumPoseInterval-1e-9;
    tooLong = gaps>cfg.measurement.maximumPoseInterval+1e-9;
    if isempty(stamps), firstPose=Inf; else, firstPose=stamps(1); end
    % Only the fully received measurement-time horizon can be audited. The
    % causal prediction tail is checked separately through the delay model.
    settled = time>=firstPose & time<=time(end)-cfg.measurement.fixedLidarDelay;
    velocityOutside = any(abs(onlineState(:,[2 5]))>cfg.operating.maximumSpeed,2);
    accelerationOutside = any(abs(onlineState(:,[3 6]))>cfg.operating.maximumAcceleration,2);
    gpsDelays=gps.arrivalTime(acceptedGps)-gps.timestamp(acceptedGps);
    if isempty(gpsDelays), maximumGpsDelay=0; else, maximumGpsDelay=max(gpsDelays); end
    conditions = struct('maximumGpsDelaySeconds',maximumGpsDelay, ...
        'fixedLagBoundCoversGpsDelay',maximumGpsDelay<=cfg.measurement.fixedLidarDelay+1e-8, ...
        'maximumQualifiedPoseGapSeconds',largestGap, ...
        'qualifiedPoseIntervals',gaps,'shortIntervalCount',nnz(tooShort), ...
        'longIntervalCount',nnz(tooLong),'fullPoseFreshAtMeasurementTime',fresh, ...
        'freshFractionAfterStartup',mean(fresh(settled)), ...
        'fixedDelayMatchesConfiguration',delayMatches, ...
        'configuredFixedDelaySeconds',cfg.measurement.fixedLidarDelay, ...
        'replayBufferCoversFixedDelay',cfg.measurement.replayBufferDuration ...
            >=cfg.measurement.fixedLidarDelay+cfg.measurement.maximumIntegrationStep, ...
        'informationRejectedCount',nnz(~lidar.qualified), ...
        'acceptedGpsEvents',nnz(acceptedGps),'availableGpsEvents',numel(gps.timestamp), ...
        'onlineVelocityOutsideEnvelope',velocityOutside, ...
        'onlineAccelerationOutsideEnvelope',accelerationOutside, ...
        'poseErrorBoundValidated',logical(cfg.lidar.errorBoundValidated), ...
        'upstreamDisturbanceBoundValidated',false,'numericalErrorBoundValidated',false, ...
        'unconditionalStabilityClaimed',false);
    conditions.timingWithinCertificate = ~isempty(gaps) && any(settled) && ~any(tooShort | tooLong) ...
        && all(fresh(settled));
end
