function measurement = registrationPoseMeasurement(result,timestamp)
% registrationPoseMeasurement Export accepted D2D pose and physical information.
% A missing matrix is an interface error. Rejected/partial matches emit no
% full-pose event. Arrival time is set by the caller when delivery occurs.
    assert(isscalar(timestamp) && isfinite(timestamp),'Invalid acquisition time.');
    measurement=[];
    if ~result.accepted, return; end
    assert(isfield(result,'information'), ...
        'VehicleLocalization:RegistrationInformationUnavailable', ...
        'Accepted D2D registration must provide its pose information matrix.');
    information=double(result.information);
    assert(isequal(size(information),[3 3]) && isreal(information) && ...
        all(isfinite(information),'all') && ...
        norm(information-information.','fro')<=1e-10*max(1,norm(information,'fro')), ...
        'VehicleLocalization:InvalidRegistrationInformation','Invalid pose information matrix.');
    [~,failure]=chol(information);
    assert(failure==0,'VehicleLocalization:InvalidRegistrationInformation', ...
        'A full accepted pose must have positive definite information.');
    measurement=struct('timestamp',double(timestamp),'arrivalTime',double(timestamp), ...
        'pose',result.poseXYTheta,'information',information);
end
