function verification = verifyImprovedObserverDesign(design,cfg)
% verifyImprovedObserverDesign Check the reference current-pose timer LMIs.
% These inequalities do not certify the fixed-delay transport runtime.
    if ~isfield(design,'kind')
        verification=verifyContinuousObserverDesign(design,cfg);return;
    end
    if string(design.kind)=="aperiodic-pose-v1"
        fixture=cfg;fixture.K=design.K;fixture.N=design.N;
        verification=verifyLidarOnlyTimerCertificate(design.timer,fixture);
        verification.certified=verification.passed;verification.productionImplemented=false;return;
    end
    assert(string(design.kind)=="aperiodic-anisotropic-pose-v2");
    c=design.timer;fixture=cfg;fixture.K=design.K;fixture.N=design.N;
    compatible=abs(cfg.observer.theta-c.theta)<1e-12 && abs(cfg.observer.sigma-c.theta)<1e-12 ...
        && max(abs(design.N-cfg.observer.invariantGain),[],'all')<1e-12 ...
        && abs(cfg.measurement.lidarMaximumAge-c.onTime)<1e-12 ...
        && abs(cfg.measurement.gpsMaximumAge-c.onTime)<1e-12 ...
        && abs(cfg.measurement.minimumPoseInterval-c.tMin)<1e-12 ...
        && abs(cfg.measurement.maximumPoseInterval-c.tMax)<1e-12 ...
        && abs(cfg.lidar.certificateMinimumPoseWeight-c.alpha)<1e-12 ...
        && isequal(cfg.lidar.poseScales(:),c.poseScales(:));
    verification=verifyAnisotropicPoseCertificate(c,fixture);
    verification.certified=compatible && verification.passed;
    verification.productionImplemented=false;
    verification.verifiedModel=struct('K',design.K,'N',design.N,'P',c.P, ...
        'multipliers',c.multipliers,'operating',cfg.operating, ...
        'scalingExponents',cfg.observer.scalingExponents,'poseScales',c.poseScales, ...
        'theta',c.theta,'knots',c.knots,'rate',c.rate,'alpha',c.alpha, ...
        'onTime',c.onTime,'tMin',c.tMin,'tMax',c.tMax);
    verification.checkedVertexCount=verification.flowInequalityCount;
    verification.scope="reference current-pose pulse LMIs; fixed-delay transport requires separate certification";
end
