function record = shaftSpeedRecord(perception)
% shaftSpeedRecord: Compact output snapshot, excluding dense diagnostics.
    candidates = perception.candidates;
    record = struct('poleCells',double(candidates.pillarIndices{ ...
        candidates.semanticNames=="pole"}), ...
        'components',perception.probabilityCloud.components, ...
        'sourceSummary',perception.sourceSummary, ...
        'semanticNames',candidates.semanticNames, ...
        'pillarIndices',{candidates.pillarIndices});
end
