function results=validateContextAlignment()
% validateContextAlignment: Physical controls, metric tests and perception regression.
    root=setupVehicleLocalization();folder=fileparts(mfilename('fullpath'));
    addpath(root); % Test fixtures may temporarily change the working directory.
    oldRoot=getenv('VEHICLE_LOCALIZATION_DATA_ROOT');
    cleanup=onCleanup(@()setenv('VEHICLE_LOCALIZATION_DATA_ROOT',oldRoot)); %#ok<NASGU>
    setenv('VEHICLE_LOCALIZATION_DATA_ROOT',fullfile(root,'data'));
    suites={'pillarFineAlignmentTest','pillarPoleValidationTest', ...
        'pillarShaftModesTest','pillarShaftExecutionTest','poleSubsetEvidenceTest', ...
        'poleDistributionEvidenceTest','pillarVerticalShapeTest','pillarRadialDistributionTest', ...
        'pillarDensityCoreTest','wholePillarPerceptionTest','coarseSemanticProbabilityCloudTest', ...
        'coarsePerceptionPerformanceTest','perceptionFeatureSelectionTest','pipelineRegressionTest', ...
        'finePoleRejectionTest','poleVerticalContinuityTest','poleBoundaryRecoveryTest'};
    paths=cellfun(@(name)fullfile(root,'tests',[name '.m']),suites,'UniformOutput',false);
    results=runtests(paths);
    T=table(string({results.Name}).',[results.Passed].',[results.Failed].', ...
        [results.Incomplete].',[results.Duration].', ...
        'VariableNames',{'Name','Passed','Failed','Incomplete','Duration'});
    writetable(T,fullfile(folder,'tests.csv'));
    save(fullfile(root,'output','pole_context_20260927','tests.mat'),'results');
    assertSuccess(results);
end
