function results=validateSemanticPrecision()
% validateSemanticPrecision: Precision contracts and existing perception tests.
    root=setupVehicleLocalization();addpath(root);folder=fileparts(mfilename('fullpath'));
    old=getenv('VEHICLE_LOCALIZATION_DATA_ROOT');restore=onCleanup(@()setenv('VEHICLE_LOCALIZATION_DATA_ROOT',old));
    setenv('VEHICLE_LOCALIZATION_DATA_ROOT',fullfile(root,'data'));
    suites={'semanticPillarPrecisionTest','pillarPoleDistributionTest','pillarFineAlignmentTest', ...
        'pillarPoleValidationTest','pillarShaftModesTest','pillarShaftExecutionTest','poleSubsetEvidenceTest', ...
        'poleDistributionEvidenceTest','pillarVerticalShapeTest','pillarRadialDistributionTest', ...
        'pillarDensityCoreTest','wholePillarPerceptionTest','coarseSemanticProbabilityCloudTest', ...
        'coarsePerceptionPerformanceTest','perceptionFeatureSelectionTest','pipelineRegressionTest', ...
        'finePoleRejectionTest','poleVerticalContinuityTest','poleBoundaryRecoveryTest', ...
        'curbGeometryRefinementTest','curbRoadSupportTest','curbBoundaryNormalTest'};
    paths=cellfun(@(name)fullfile(root,'tests',[name '.m']),suites,'UniformOutput',false);
    results=runtests(paths);T=table(string({results.Name}).',[results.Passed].',[results.Failed].', ...
        [results.Incomplete].',[results.Duration].','VariableNames',{'Name','Passed','Failed','Incomplete','Duration'});
    writetable(T,fullfile(folder,'tests.csv'));assertSuccess(results);
end
