function assertMncavReplayCurrent(parameters)
% assertMncavReplayCurrent Reject cached inputs using obsolete vehicle/steering.
    current=mncavReplayConfig();
    assert(isfield(parameters,'vehicle') && isequaln(parameters.vehicle,current.vehicle) && ...
        isfield(parameters,'steeringRatio') && parameters.steeringRatio==current.steeringRatio && ...
        isfield(parameters,'steeringWheelOffsetRad') && ...
        parameters.steeringWheelOffsetRad==current.steeringWheelOffsetRad, ...
        'VehicleLocalization:StaleReplayConfiguration', ...
        'Cached inputs use an obsolete or undocumented MnCAV vehicle/steering configuration. Rebuild the upstream replay with mncavReplayConfig before this experiment.');
end
