function cfg=curbBoundaryGeometryConfig()
% curbBoundaryGeometryConfig Continuous curb geometry on selected coarse pillars.
% Engineering support and scatter bounds, not calibrated confidence intervals.
    cfg=struct('enabled',false,'directionRadius',2.4,'minimumAnisotropy',4, ...
        'supportRadius',1.6,'tangentHalfWidth',1.2,'normalHalfWidth',.9, ...
        'minimumPoints',20,'minimumNormalSpan',.6,'maximumBoundaryShift',.7, ...
        'maximumCandidates',64,'faceHalfWidth',.06,'minimumHeight',.04, ...
        'maximumHeight',.30,'minimumExplainedFraction',.25, ...
        'maximumResidualStd',.06,'minimumFacePoints',3,'minimumNormalVariance',.01);
    cfg.lineSupport=struct('radius',4,'minimumComponents',3, ...
        'minimumAnisotropy',9,'minimumSpan',2.4,'standardDeviation',deg2rad(1));
end
