function cfg=downtownCandidateConfig(spacing,candidatePolicy)
% downtownCandidateConfig: Whole-pillar statistical candidate operating points.
% Downtown's default balances precision with buffered calibration recall.
% Legacy 0.6 m classifiers remain available for explicit configurations only.
    if nargin<2,candidatePolicy="precision";end
    candidatePolicy=string(candidatePolicy);
    assert(isscalar(candidatePolicy) && any(candidatePolicy==["precision","strictPrecision","highRecall"]), ...
        'perception:DowntownCandidatePolicy','Use precision, strictPrecision or highRecall.');
    cfg=struct('spacing',spacing,'useModels',spacing>.3, ...
        'modelDirectory',fileparts(mfilename('fullpath')), ...
        'modelFiles',struct(),'curbHaloMeters',0, ...
        'curbExtensionMeters',16,'curbExtensionHalfWidthMeters',0.3, ...
        'structuralHaloMeters',0.3,'facadeHaloMeters',3.0, ...
        'curbExtensionMinimumTotalEnergy',.07,'curbExtensionMinimumBaseEnergy',.20, ...
        'curbExtensionMinimumHeightStep',.025,'curbExtensionMinimumCenterEvidence',.90, ...
        'curbExtensionMaximumRelativeHeight',.25, ...
        'poleDistributionGate',struct('enabled',spacing<.6,'radiusCells',1, ...
            'minimumVerticalVarianceFraction',.90,'maximumRadialVariance',.10), ...
        'signMinimumReflectiveMeanClearance',1.0);
    cfg.modelFiles=struct('curb','downtownCurbStatisticsModel.json', ...
        'facade','downtownFacadeStatisticsModel.json','pole','downtownPoleStatisticsModel.json', ...
        'trafficSign','downtownTrafficSignStatisticsModel.json');
    cfg.candidatePolicy=candidatePolicy;
    cfg.precisionFilter=struct('enabled',spacing<.6 && candidatePolicy~="highRecall",'rules',struct());
    if cfg.precisionFilter.enabled
        filename='downtownBalancedRules.json';
        if candidatePolicy=="strictPrecision",filename='downtownPrecisionRules.json';end
        cfg.precisionFilter.rules=jsondecode(fileread(fullfile(fileparts(mfilename('fullpath')), ...
            filename)));
    end
end
