function cfg = downtownStructuralConfig(spacing)
% downtownStructuralConfig: Downtown reviewV12 structural acceptance rules.
% Sparse height evidence is formed on the existing XY pillar lattice. Pole
% shape, attachment and sign clearance limits retain their physical units.
    if nargin<1, spacing=0.3; end
    cfg.heightResolution = 0.5;
    cfg.intensityThreshold = 1600;
    cfg.candidate = fineStructuralConfig();
    cfg.candidate.poleOccupiedLayerMinPoints = 1;
    cfg.candidate.useNativeKernels = false;
    cfg.slice = struct('minimumCandidateLayers',4,'minimumLayerPoints',2, ...
        'minimumSliceRatio',0.60,'minimumMeanRatio',0.70,'minimumTotalRatio',0.70, ...
        'minimumPointScore',0.70,'allowRelaxed',true, ...
        'relaxedMaximumBaseHeight',0.5,'relaxedMinimumMeanRatio',0.75, ...
        'relaxedMinimumTotalRatio',0.70);
    cfg.pointShape = struct('enabled',true,'minPoints',8,'minHeightMeters',2.0, ...
        'minPrincipalVarianceFraction',0.99,'maxAxisTiltDegrees',15, ...
        'maxVerticalGapMeters',0.8,'axisProfile',struct('enabled',true, ...
        'sliceHeightMeters',0.40,'maxResidualStepMeters',0.15,'maxLargeStepCount',1));
    cfg.context = struct('enabled',true,'coreRadiusMeters',0.20, ...
        'contactRadiusMeters',0.40,'contextRadiusMeters',0.80, ...
        'endMarginMeters',0.35,'sliceHeightMeters',0.40, ...
        'minContextPointsPerSlice',3,'minContactPointsPerSlice',2, ...
        'minContactSlices',3,'minCrowdedSliceFraction',0.50, ...
        'minObjectToContextPointRatio',0.50);
    cfg.context.lateralAttachment = struct('enabled',true, ...
        'contextRadiusMeters',2.0,'halfHeightMeters',0.25, ...
        'heightStepMeters',0.20,'maxPointGapMeters',0.30, ...
        'minExternalPoints',8,'minReachMeters',1.20,'minHeightSeparationMeters',1.0);
    cfg.denseRecovery = struct('enabled',true,'supportRadiusCells',1, ...
        'maxFootprintSpanCells',2,'minPoints',80,'minHeightMeters',1.0, ...
        'maxHeightMeters',2.0,'maxFootprintDiagonalMeters',0.35, ...
        'minPrincipalVarianceFraction',0.97,'maxAxisTiltDegrees',5, ...
        'maxVerticalGapMeters',0.10,'sliceHeightMeters',0.20, ...
        'minSlicePoints',4,'minPopulatedSliceFraction',0.85, ...
        'contextRadiusCells',max(1,round(0.6/spacing)), ...
        'minObjectToContextPointRatio',0.90);
    cfg.signSupport = struct('enabled',true,'minCandidatePoints',3, ...
        'minHeightAboveGroundMeters',1.5,'groundSearchRadiusMeters',4.0, ...
        'groundCellSizeMeters',0.5,'groundCellHeightQuantile',0.20, ...
        'minGroundPoints',12,'minGroundCells',6,'maxNearestGroundDistanceMeters',2.0, ...
        'groundFitIterations',3,'groundResidualToleranceMeters',0.15, ...
        'minGroundInlierFraction',0.70,'maxGroundRmsMeters',0.08,'maxGroundSlope',0.25);
end
