function cfg=downtownCandidateConfig(spacing)
% downtownCandidateConfig: Whole-pillar statistical candidate operating points.
% Offline envelopes favor recall before point/neighborhood rejection. Online
% classifiers use current-frame pillar statistics only, with no fine calls.
    cfg=struct('spacing',spacing,'useModels',spacing>.3, ...
        'modelDirectory',fileparts(mfilename('fullpath')), ...
        'modelFiles',struct(),'curbHaloMeters',0.6, ...
        'curbExtensionMeters',16,'curbExtensionHalfWidthMeters',0.3, ...
        'structuralHaloMeters',0.6,'facadeHaloMeters',3.0, ...
        'curbExtensionMinimumTotalEnergy',.07,'curbExtensionMinimumBaseEnergy',.20, ...
        'curbExtensionMinimumHeightStep',.025,'curbExtensionMinimumCenterEvidence',.90, ...
        'curbExtensionMaximumRelativeHeight',.25);
    cfg.modelFiles=struct('curb','downtownCurbStatisticsModel.json', ...
        'facade','downtownFacadeStatisticsModel.json','pole','downtownPoleStatisticsModel.json', ...
        'trafficSign','downtownTrafficSignStatisticsModel.json');
end
