function cfg = finePerceptionConfig()
% finePerceptionConfig: Offline point validation in metric coordinates.
% Geometry limits describe vertical poles and facades; robustScale controls
% distance rejection about the fitted line or plane. No online dependency.
    cfg = struct("poleMinimumHeight", 1.0, "poleMaximumRadius", 0.35, ...
        "poleMaximumTiltDegrees", 20, "poleMinimumPoints", 6, ...
        "robustScale", 3.0, "minimumResidualScale", 0.02, ...
        "poleMinimumSliceRatio", 0.60, "poleMinimumSupportRatio", 0.70, ...
        "poleMinimumSupportedHeight", 1.5, ...
        "facadeMinimumPoints", 12, "facadeMinimumHeight", 1.0, ...
        "facadeMinimumLength", 1.0, "facadeMaximumDistance", 0.20, ...
        "facadeMaximumNormalAngleDegrees", 20);
end
