function cfg = finePerceptionConfig()
% finePerceptionConfig: Offline point validation in metric coordinates.
% Geometry limits describe a vertical pole; robustScale controls outlier
% rejection relative to its fitted local radius. No online dependency.
    cfg = struct("poleMinimumHeight", 1.0, "poleMaximumRadius", 0.35, ...
        "poleMaximumTiltDegrees", 20, "poleMinimumPoints", 6, ...
        "robustScale", 3.0, "minimumResidualScale", 0.02, ...
        "poleMinimumSliceRatio", 0.60, "poleMinimumSupportRatio", 0.70, ...
        "poleMinimumSupportedHeight", 1.5);
end
