function cfg=lidarImuTiltConfig()
% lidarImuTiltConfig Causal gravity-direction filter in stored point axes.
% Time constants are physical smoothing times, not fitted to reference poses.
% Wheel acceleration and v*r approximate planar translational acceleration;
% slip, grades, accelerometer bias and IMU lever-arm dynamics remain errors.
    cfg=struct('schemaVersion',1,'gravityMps2',9.80665, ...
        'correctionTimeSeconds',3,'speedTimeSeconds',.25, ...
        'stationarySpeedMps',.08,'stationaryGyroRadps',deg2rad(5), ...
        'minimumAlignmentSeconds',1,'maximumGravityNormErrorMps2',2, ...
        'maximumImuAgeSeconds',.05,'maximumWheelAgeSeconds',.15, ...
        'maximumImuStepSeconds',.1,'mode',"imu");
end
