function cfg=mncavVdbConfig()
% mncavVdbConfig Canonical MnCAV anchors and explicit high-fidelity assumptions.
% Unknown suspension/tire/vertical parameters are engineering assumptions,
% not identified MnCAV properties. The generated MathWorks model stays in output.
    p=mncavVehicleConfig();cfg=struct('schemaVersion',1,'vehicle',p.vehicle,'stock',p.stock, ...
        'steeringRatio',p.steeringRatio,'source','config/mncavVehicleParameters.json');
    cfg.body=struct('cgHeightM',.62,'rollInertiaKgM2',900,'pitchInertiaKgM2',4200, ...
        'dragCoefficient',.32,'frontalAreaM2',2.9);
    tire=sscanf(p.stock.standardTireSize,'%f/%fR%f');assert(numel(tire)==3);
    width=tire(1)/1000;aspect=tire(2)/100;rim=tire(3)*.0254/2;
    cfg.wheel=struct('unsprungMassKg',[50 50 50 50],'spinInertiaKgM2',1.8, ...
        'unloadedRadiusM',width*aspect+rim, ...
        'widthM',width,'rimRadiusM',rim,'aspectRatio',aspect, ...
        'verticalStiffnessNpm',250000,'verticalDampingNspm',700,'pressurePa',250000);
    cfg.suspension=struct('springRateNpm',[40000 40000 38000 38000], ...
        'damperRateNspm',[3500 3500 3200 3200]);
    cfg.simulation=struct('maximumStepSeconds',.002,'sampleTimeSeconds',.01, ...
        'settleSeconds',3,'maximumSpeedMps',8,'lateralAccelerationMps2',2, ...
        'longitudinalAccelerationMps2',1.5,'maximumBrakeMps2',2,'seed',20261002);
    cfg.driver=struct('lookaheadBaseM',3,'lookaheadTimeSeconds',.65, ...
        'steeringTimeConstantSeconds',.12,'maximumRoadWheelAngleRad',.5, ...
        'maximumSteeringRateRadps',.5,'speedGain',1.2);
    sensor=mncavSensorConfig();
    cfg.sensors=struct('imuPeriodSeconds',1/sensor.observerImu.nativeRateHz,'lidarPeriodSeconds',.1, ...
        'gnssPeriodSeconds',.1,'lidarHeightAboveNominalRoadM',2, ...
        'accelerometerNoiseStdMps2',sensor.lateralSimulation.lateralAccelerationNoiseStdMps2, ...
        'gyroNoiseStdRadps',sensor.lateralSimulation.yawRateNoiseStdRadps, ...
        'wheelNoiseStdRadps',.01,'steeringNoiseStdRad',.0005, ...
        'gnssNoiseStdM',sensor.referenceGnssIns.positionErrorSimulationPriorM, ...
        'lidarRangeNoiseStdM',.015);
    cfg.assumptions="Generic independent kinematics/compliance suspension and Magic Formula 6.2 tire coefficients, " + ...
        "matched to stock tire dimensions and adopted nominal axle cornering stiffness. Dry flat Town10 road, " + ...
        "no aerodynamic wind; front-wheel torque actuation with steering lag, not an identified Pacifica hybrid powertrain.";
end
