function cfg=pillarPoleValidationConfig()
% pillarPoleValidationConfig: Continuous support validation on coarse pillars.
% All distances are meters. The measurement radius is not an auxiliary grid.
% Development used original fine labels. Sparse temporal and Downtown checks
% exposed losses from strict owner/shape gates; the final profile favors coverage.
    cfg=struct('radii',.25,'contextRadius',.75,'searchHalfWidth',1.5, ...
        'halfWindow',.25,'minimumWindowPoints',3,'minimumWindowFraction',.60, ...
        'minimumSupportHeight',1.5,'minimumMeanRatio',.70,'minimumMassRatio',.70, ...
        'shortSupportHeight',2,'minimumShortRun',1.5, ...
        'maximumTilt',10,'maximumShortTilt',6,'maximumRms',.20,'maximumShortRms',.10, ...
        'maximumStd',.12,'maximumShortStd',.09,'maximumAspect',3, ...
        'minimumIsolation',.80,'weakMinimumIsolation',.80,'strongMeanRatio',.80, ...
        'denseMinimumPoints',100,'denseMinimumContrast',10,'denseMaximumTilt',1,'denseMaximumRms',.06, ...
        'isolationCoreRadius',.25,'minimumRadialScale',.02,'maximumTrimRadius',.35, ...
        'trimMadMultiplier',3,'weakTrimRadius',.10, ...
        'poleMaximumVerticalGapMeters',.75,'poleMinimumPoints',6,'poleMinimumHeight',1, ...
        'minimumOwnerPoints',10,'minimumOwnerHeight',.30,'minimumPointScore',0);
end
