function cfg=pillarShaftConfig()
% pillarShaftConfig: Metric distribution tests for bounded pole-shaft modes.
% Hypotheses and height endpoints come from returns in existing XY pillars.
% No auxiliary lattice or whole-pillar foreground fraction is required.
% Radial significance is an adaptive concentration score, not a calibrated
% hypothesis-test statistic or a probability of a physical pole.
    cfg=struct('maximumSeeds',4,'seedSeparation',.08,'fitHeight',2.0, ...
        'heightHypotheses',2,'neighborhoodRadius',.75, ...
        'minimumPoints',10,'minimumOwnPoints',4,'minimumOwnHeight',.35, ...
        'minimumHeight',1.3,'minimumRobustHeight',1.0,'maximumTiltDegrees',20, ...
        'maximumGap',.5,'rangeGapScale',.005,'maximumRadialRms',.10, ...
        'minimumPeakContrast',1.2,'minimumExcessPoints',3, ...
        'minimumRadialSignificance',2.5,'maximumRelativeRadialRms',.65, ...
        'minimumHalfRadialSignificance',3,'minimumHalfPeakContrast',1.05, ...
        'maximumIntervalEndpoints',12,'minimumScore',.30, ...
        'saturatedHeight',2.0,'saturatedPoints',20, ...
        'axisMergeDistance',.025,'axisMergeSlope',.015,'minimumFitScales',1, ...
        'minimumSingleScaleScore',.65,'shaftMergeDistance',.12, ...
        'shaftMergeSlope',.10,'shaftMergeMinimumOverlap',.5, ...
        'minimumAssignedPoints',3,'minimumAssignedHeight',.30, ...
        'strongScore',.70,'minimumShapeProduct',.25, ...
        'verticalHypotheses',true,'radii',[.06 .10 .15],'fitRadii',[.10 .20]);
end
