function cfg=pillarPoleValidationConfig()
% pillarPoleValidationConfig: Continuous support validation on coarse pillars.
% All distances are meters. The measurement radius is not an auxiliary grid.
% Sparse shafts/owners must satisfy tighter tilt and residual limits; these
% conditional gates preserve tight sparse poles instead of a hard count cut.
% Set both sparse point thresholds to zero to reproduce the preceding profile.
    cfg=struct('radii',.25,'contextRadius',.75,'searchHalfWidth',1.5, ...
        'halfWindow',.25,'minimumWindowPoints',3,'minimumWindowFraction',.60, ...
        'minimumSupportHeight',1.5,'minimumMeanRatio',.70,'minimumMassRatio',.70, ...
        'shortSupportHeight',2,'minimumShortRun',1.5, ...
        'maximumTilt',10,'maximumShortTilt',6,'maximumRms',.20,'maximumShortRms',.10, ...
        'maximumStd',.12,'maximumShortStd',.09,'maximumAspect',3, ...
        'minimumIsolation',.80,'weakMinimumIsolation',.80,'strongMeanRatio',.80, ...
        'denseMinimumPoints',100,'denseMinimumContrast',10,'denseMaximumTilt',1,'denseMaximumRms',.06, ...
        'isolationCoreRadius',.25,'minimumRadialScale',.02,'maximumTrimRadius',.35, ...
        'trimMadMultiplier',3,'weakTrimRadius',.10, ...
        'poleMaximumVerticalGapMeters',.75,'poleMinimumPoints',6,'poleMinimumHeight',1, ...
        'minimumOwnerPoints',10,'minimumOwnerHeight',.30,'minimumPointScore',0, ...
        'sparseSupportPointThreshold',30,'sparseOwnerPointThreshold',15, ...
        'maximumSparseTilt',4,'maximumSparseRms',.10, ...
        'sparseRelaxationRange',[15 20],'maximumDistantSparseTilt',6, ...
        'maximumDistantSparseRms',.12);
end
