function cfg=robustPoseGraphConfig()
% robustPoseGraphConfig Experimental causal SE(2) graph with switchable map factors.
% Noise scales are engineering settings, not calibrated sensor specifications.
    cfg=struct('maximumFrames',10,'maximumIterations',12,'stepTolerance',1e-5, ...
        'motionStandardDeviation',[.04 .04 deg2rad(.2)], ...
        'initialStandardDeviation',[.5 .5 deg2rad(3)], ...
        'featureLoss',"switchable",'switchPrior',6.25,'gnssRobustScale',9.21, ...
        'lidarInformationScale',1,'registration',distributionRegistrationConfig());
end
