function cfg = temporalStabilityMapConfig()
% temporalStabilityMapConfig: Repeated-observation Gaussian field parameters.
% Lengths are meters, covariances are square meters, and reference mass is
% occupied XY area. Defaults are engineering assumptions, not calibration.
    cfg = struct('schemaVersion',2,'classes',strings(0,1), ...
        'observationBlockSize',1,'blockOriginFrame',1, ...
        'minimumConditionalHeightVariance',1e-4,'logEnabled',false);
    cfg.frameCalibration=lidarFrameCalibrationConfig();
    cfg.defaultParams = parameters("");
    cfg.classParams = arrayfun(@parameters, ...
        ["curb";"facade";"pole";"trafficSign"]);
end

function p = parameters(name)
    p = struct('classLabel',name, ...
        'representativeResolution',0.10,'referenceResolution',0.25, ...
        'tileSize',8.0,'tileOrigin',[-4 -4],'contextHalo',2.0, ...
        'maxComponentsPerTile',3,'minComponentPoints',2, ...
        'minObservedBlocks',2,'minBlockEffectiveCount',0.5, ...
        'repeatabilityPrior',0.5,'stableStandardDeviation',0.15, ...
        'variableStandardDeviation',1.0,'tangentStandardDeviation',1.0, ...
        'elongatedAnisotropyThreshold',4.0,'meanPriorStandardDeviation',8.0, ...
        'minCovarianceEigenvalue',0.0025,'maxCovarianceEigenvalue',16.0, ...
        'mixturePseudocount',0.1,'backgroundBetaPrior',[2 10], ...
        'publishFalsePositiveCost',1.0,'publishFalseNegativeCost',1.0, ...
        'emMaxIterations',80,'emTolerance',1e-5,'parameterTolerance',1e-3, ...
        'selectionMinBlocks',3,'selectionHoldoutEvery',3, ...
        'selectionMinGainPerPoint',0.01,'storeEmAssignments',false, ...
        'clutterIntensity',0.05,'classImportance',1.0, ...
        'queryIntensityTolerance',1e-7,'queryIndexCellSize',2.0, ...
        'heightModeSeparation',0.75,'heightModeVarianceRatio',0.25);
end
