function cfg=wheelSpeedObserverConfig()
% wheelSpeedObserverConfig MnCAV wheel geometry and independent-drive fit.
% Effective radii/lag coefficients are empirical input corrections, not
% independently measured tire radii or physical sensor delivery delays.
    root=fileparts(mfilename('fullpath'));
    fit=jsondecode(fileread(fullfile(root,'mncavWheelSpeedCalibration.json')));
    cfg=struct('effectiveRadius',reshape(fit.effectiveRadiusM,1,4), ...
        'lagCompensation',reshape(fit.lagCompensationSeconds,1,4), ...
        'wheelbase',3.089,'frontTrack',1.734,'rearTrack',1.735, ...
        'rearCgDistance',1.714395,'filterTimeConstant',.01, ...
        'maximumWheelAge',.15,'consensusThreshold',.15,'maximumWheelRate',200, ...
        'maximumSteeringAngle',.6,'stationaryWheelRate',.05, ...
        'stationaryYawRate',.03,'method',"robust",'initialSpeed',NaN);
end
