function cfg=wheelSpeedObserverConfig()
% wheelSpeedObserverConfig MnCAV wheel geometry and independent-drive fit.
% Effective radii/lag coefficients are empirical input corrections, not
% independently measured tire radii or physical sensor delivery delays.
    root=fileparts(mfilename('fullpath'));
    fit=jsondecode(fileread(fullfile(root,'mncavWheelSpeedCalibration.json')));
    parameters=mncavVehicleConfig();
    cfg=struct('effectiveRadius',reshape(fit.effectiveRadiusM,1,4), ...
        'lagCompensation',reshape(fit.lagCompensationSeconds,1,4), ...
        'wheelbase',parameters.vehicle.lf+parameters.vehicle.lr, ...
        'frontTrack',parameters.stock.frontTrackM,'rearTrack',parameters.stock.rearTrackM, ...
        'rearCgDistance',parameters.vehicle.lr,'filterTimeConstant',.01, ...
        'maximumWheelAge',.15,'consensusThreshold',.15,'maximumWheelRate',200, ...
        'maximumSteeringAngle',.6,'stationaryWheelRate',.05, ...
        'stationaryYawRate',.03,'method',"robust",'initialSpeed',NaN);
end
