function checkCode()
% checkCode Record factory analysis for the implementation and study runners.
    setupVehicleLocalization();dest=fileparts(mfilename('fullpath'));
    files=["config/distributionRegistrationConfig.m","localization/sourceLineDirections.m", ...
        "localization/prepareSemanticRegistrationGeometry.m","localization/registerSemanticProbabilityCloud.m", ...
        "tests/lineDirectionRegistrationTest.m", ...
        "research/line_direction_matching_20260928/screenDirection.m", ...
        "research/line_direction_matching_20260928/screenWindow.m", ...
        "research/line_direction_matching_20260928/evaluateDirection.m", ...
        "research/line_direction_matching_20260928/evaluateAssociation.m", ...
        "research/line_direction_matching_20260928/runProduction.m", ...
        "research/line_direction_matching_20260928/inspectProduction601.m", ...
        "research/line_direction_matching_20260928/checkCode.m"];
    issues=cell(numel(files),1);for k=1:numel(files),issues{k}=checkcode(files(k),'-config=factory');end
    fid=fopen(fullfile(dest,'code_analysis.json'),'w');fprintf(fid,'%s\n',jsonencode(struct('files',files,'issues',{issues})));fclose(fid);
    disp(issues);
end
