function audit=auditMncavFullLocalizationExperiment(folder)
% auditMncavFullLocalizationExperiment Compare both outputs at identical scans.
% Includes rejection predictions, real lateral participation and actual gains.
    arguments
        folder (1,1) string="output/mncav_full_localization_20260914"
    end
    setupVehicleLocalization;
f=load(fullfile(folder,'full_experiment.mat'));calls=readtable(fullfile(folder,'matching','calls.csv'));
writetable(calls(:,{'frame','timeSeconds','accepted','directionalAccepted','reason', ...
    'positionErrorM','yawErrorDeg','totalMs','perceptionMs','registrationMs'}), ...
    fullfile(folder,'matching_errors.csv'));
rows=1:10:numel(f.estimate.time);
writetable(table(f.estimate.time(rows),vecnorm(f.error(rows,1:2),2,2),rad2deg(f.error(rows,3)), ...
    'VariableNames',{'time','positionErrorM','headingErrorDeg'}),fullfile(folder,'observer_errors_10hz.csv'));
mask=calls.timeSeconds>=f.estimate.time(1)&calls.timeSeconds<=f.estimate.time(end);
time=calls.timeSeconds(mask);observed=interp1(f.estimate.time,f.estimate.pose,time,'linear');
% Compare both estimates against exactly the same scan-associated reference.
scanReference=[calls.referenceX(mask),calls.referenceY(mask),calls.referencePsi(mask)];
scanError=observed-scanReference;scanError(:,3)=atan2(sin(scanError(:,3)),cos(scanError(:,3)));
matchedError=[calls.positionErrorM(mask),calls.yawErrorDeg(mask)];
audit=struct('commonScanCount',nnz(mask),'observerAtScanPositionRmseM',rms(vecnorm(scanError(:,1:2),2,2)), ...
 'matchingAtSameScanPositionRmseM',rms(matchedError(:,1)), ...
 'observerAtScanHeadingRmseDeg',rad2deg(rms(scanError(:,3))), ...
 'matchingAtSameScanHeadingRmseDeg',rms(matchedError(:,2)), ...
 'maximumPositionErrorTimeSeconds',f.estimate.time(find(vecnorm(f.error(:,1:2),2,2)==max(vecnorm(f.error(:,1:2),2,2)),1)), ...
 'maximumAbsoluteEstimatedVelocityComponent',max(abs(f.estimate.z(:,[2,5])),[],'all'), ...
 'maximumAbsoluteEstimatedAccelerationComponent',max(abs(f.estimate.z(:,[3,6])),[],'all'), ...
 'dynamicModelSamples',nnz(f.lateral.diagnostics.dynamicModelEvaluated), ...
 'stationarySamples',nnz(f.lateral.diagnostics.stationaryDetected), ...
 'maximumLateralVelocityMps',max(abs(f.lateral.lateralVelocity)), ...
 'lateralGainAt8Mps',scheduleLateralObserverGain(f.lateralDesign,8));
D=buildImprovedObserverCertificateData(f.cfg);audit.physicalPoseGain=D.T*f.design.K;
audit.physicalAuxiliaryGain=D.T*f.design.N/f.cfg.observer.theta^3;
[~,~,strictWeight]=computeLidarInformationWeights(f.data.lidar.information(:,:,1),improvedObserverConfig('lidar','mncav'));
audit.firstReconstructedWeightPassesHistoricalScale=strictWeight.qualified;

fid=fopen(fullfile(folder,'audit.json'),'w');fprintf(fid,'%s\n',jsonencode(audit,PrettyPrint=true));fclose(fid);disp(audit);

end
