function metadata=exportLocalizationVideoData(outputFolder)
% exportLocalizationVideoData Export the final frozen experiment for display.
% Reference values enter visualization only. No estimator is re-run.
% prepareLocalizationVideoClouds.py separately reads only needed point fields.
% No perception reprocessing or bulk point-cloud read is needed here.
    arguments
        outputFolder (1,1) string="output/localization_video_20260916"
    end
    setupVehicleLocalization();if ~isfolder(outputFolder),mkdir(outputFolder);end
    selected=load('output/mncav_interface_audit_20260916/correction_experiment.mat','runs');
    original=load('output/mncav_inspva_observer_20260915/experiment.mat','experiments');
    r=selected.runs{1,4};e=original.experiments{1};
    assert(isequal(r.data.highRate.time,e.data.highRate.time));
    t=r.estimate.time;reference=e.reference;estimate=[r.estimate.position,r.estimate.headingUnwrapped];
    positionError=vecnorm(estimate(:,1:2)-reference(:,1:2),2,2);
    headingError=atan2(sin(estimate(:,3)-reference(:,3)),cos(estimate(:,3)-reference(:,3)));
    trajectory=[t,reference,estimate,r.data.highRate.longitudinalSpeed,positionError,headingError];
    writetable(array2table(trajectory,VariableNames={'time','truthX','truthY','truthYaw', ...
        'estimateX','estimateY','estimateYaw','speedMps','positionErrorM','headingErrorRad'}), ...
        fullfile(outputFolder,'trajectory.csv'));
    p=load('output/mississippi_mapping_inspva_20260915/feature_observations.mat','featureData');
    data=p.featureData;frameTime=data.framePoseTable.receiver_time_sec;
    assert(isequal(data.frameIndices(:),(1:1170).') && max(abs(t(e.frameIndices)-frameTime))<1e-9);
    calls=readtable('output/saved_perception_inspva_20260915/calls.csv',TextType="string");
    calls=calls(calls.mode=="per_frame_zero",:);
    assert(isequal(calls.frame,data.frameIndices(:)));
    status=double(calls.fullPose)+2*double(calls.directionalPose);
    frameMetadata=[data.frameIndices(:),frameTime,status,data.counts];
    writetable(array2table(frameMetadata,VariableNames={'frame','time','measurementStatus', ...
        'curbPoints','polePoints','trafficSignPoints'}),fullfile(outputFolder,'frames.csv'));
    uniformIndices=e.uniformIndices;
    metadata=struct('experiment',"steering_and_lidar_bias / per_frame_zero", ...
        'sourceExperiment',"output/mncav_interface_audit_20260916/correction_experiment.mat", ...
        'perceptionSource',"output/mississippi_mapping_inspva_20260915/feature_observations.mat", ...
        'rawPointSource',"data/raw/MissisipiPointClouds.mat", ...
        'coordinates',"EPSG:32615; grid yaw; recorded INS output point", ...
        'time',"INSPVA receiver seconds relative to first LiDAR frame", ...
        'frames',1170,'durationSeconds',frameTime(end), ...
        'semanticCounts',sum(data.counts,1),'rawDisplayPointLimit',10000, ...
        'rawDisplayBoundsM',[-15,55,-32,32,-4,10],'semanticSelectionChanged',false, ...
        'uniformSamples',numel(uniformIndices),'uniformPositionRmseM',rms(positionError(uniformIndices)), ...
        'uniformHeadingRmseDeg',rad2deg(rms(headingError(uniformIndices))), ...
        'estimatorRerun',false,'visualizationReferenceOnly',true, ...
        'limitations',"Offline replay; same-drive map and reference-seeded matching; imagery is context, not accuracy reference");
    fid=fopen(fullfile(outputFolder,'data_metadata.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
    fprintf(fid,'%s\n',jsonencode(metadata,PrettyPrint=true));
    disp(metadata);
end
