function metadata=exportLocalizationVideoData(outputFolder,sourceExperiment)
% exportLocalizationVideoData Export a frozen synchronous experiment for video.
% Reference values enter visualization only. No estimator or perception rerun.
    arguments
        outputFolder (1,1) string="output/localization_video_20260917"
        sourceExperiment (1,1) string="output/mncav_bestpos_alignment_20260917/experiment.mat"
    end
    setupVehicleLocalization();if ~isfolder(outputFolder),mkdir(outputFolder);end
    source=load(sourceExperiment,'runs','data','reference','report');
    r=source.runs{1}.estimate;
    assert(source.runs{1}.scenario=="both",'Export the complete both-channel run.');
    t=r.time;reference=source.reference;estimate=[r.position,r.headingUnwrapped];
    assert(isequal(t,source.data.highRate.time) && isequal(t,source.data.lidar.time));
    positionError=vecnorm(estimate(:,1:2)-reference(:,1:2),2,2);
    headingError=atan2(sin(estimate(:,3)-reference(:,3)),cos(estimate(:,3)-reference(:,3)));
    trajectory=[t,reference,estimate,source.data.highRate.longitudinalSpeed,positionError,headingError];
    writetable(array2table(trajectory,VariableNames={'time','truthX','truthY','truthYaw', ...
        'estimateX','estimateY','estimateYaw','speedMps','positionErrorM','headingErrorRad'}), ...
        fullfile(outputFolder,'trajectory.csv'));
    p=load('output/mississippi_mapping_inspva_20260915/feature_observations.mat','featureData');
    data=p.featureData;
    % Matching CSV round-trips lose a few decimal places in receiver seconds.
    [found,indices]=ismembertol(t,data.framePoseTable.receiver_time_sec,1e-9,DataScale=1);
    assert(all(found),'Each output needs an actual perception frame.');
    calls=readtable('output/saved_perception_inspva_20260915/calls.csv',TextType="string");
    calls=calls(calls.mode=="per_frame_zero",:);calls=calls(indices,:);
    assert(isequal(calls.frame,reshape(data.frameIndices(indices),[],1)) && isequal(calls.time,t));
    assert(isequal(logical(calls.fullPose),source.data.lidar.valid));
    status=double(calls.fullPose)+2*double(calls.directionalPose);
    frameMetadata=[calls.frame,t,status,data.counts(indices,:)];
    writetable(array2table(frameMetadata,VariableNames={'frame','time','measurementStatus', ...
        'curbPoints','polePoints','trafficSignPoints'}),fullfile(outputFolder,'frames.csv'));
    accepted=source.data.lidar.valid;
    lidarError=vecnorm(source.data.lidar.pose(accepted,1:2)-reference(accepted,1:2),2,2);
    expected=source.report.metrics(source.report.metrics.scenario=="both" & source.report.metrics.population=="full",:);
    assert(abs(rms(positionError)-expected.positionRmseM)<1e-12);
    metadata=struct('experiment',"Aligned BESTPOS + LiDAR / both channels / synchronous", ...
        'sourceExperiment',sourceExperiment, ...
        'perceptionSource',"output/mississippi_mapping_inspva_20260915/feature_observations.mat", ...
        'rawPointSource',"data/raw/MissisipiPointClouds.mat", ...
        'coordinates',"EPSG:32615; grid yaw; recorded INS output point", ...
        'time',"INSPVA receiver seconds relative to first LiDAR frame", ...
        'frames',numel(t),'firstPerceptionFrame',calls.frame(1),'lastPerceptionFrame',calls.frame(end), ...
        'durationSeconds',t(end),'excludedPerceptionFramesOutsideObserverCoverage',numel(data.frameIndices)-numel(t), ...
        'maximumPerceptionClockRoundTripSeconds',max(abs(t-data.framePoseTable.receiver_time_sec(indices))), ...
        'semanticCounts',sum(data.counts(indices,:),1),'rawDisplayPointLimit',10000, ...
        'rawDisplayBoundsM',[-15,55,-32,32,-4,10],'semanticSelectionChanged',false, ...
        'localizationSamples',numel(t),'localizationRateHz',1/median(diff(t)), ...
        'positionRmseM',rms(positionError),'positionMedianM',median(positionError), ...
        'positionP95M',prctile(positionError,95),'positionMaximumM',max(positionError), ...
        'headingRmseDeg',rad2deg(rms(headingError)), ...
        'acceptedLidarSamples',nnz(accepted),'acceptedFusionPositionRmseM',rms(positionError(accepted)), ...
        'acceptedLidarPositionRmseM',rms(lidarError), ...
        'displaySampling',"Hold latest actual synchronized state and perception; no display-state interpolation", ...
        'estimatorRerun',false,'visualizationReferenceOnly',true, ...
        'limitations',"Offline replay; same-drive map and reference-seeded matching; imagery is context, not accuracy reference");
    fid=fopen(fullfile(outputFolder,'data_metadata.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
    fprintf(fid,'%s\n',jsonencode(metadata,PrettyPrint=true));disp(metadata);
end
