function time = receiverClockTime(clock,stamp)
% receiverClockTime Apply the shared offline timestamp model in receiver seconds.
% An affine clock removes publication jitter from the clock anchors. It does
% not establish absolute sensor latency or the start/end epoch of a scan.
    arguments
        clock (1,1) struct
        stamp double
    end
    fields={'schemaVersion','method','sourceOriginSeconds','scale','offsetSeconds', ...
        'sourceSpanSeconds','maximumExtrapolationSeconds'};
    assert(all(isfield(clock,fields)) && clock.schemaVersion==1 && ...
        string(clock.method)=="robust_affine_receiver_clock", ...
        'VehicleLocalization:InvalidReceiverClock','Unsupported receiver clock model.');
    values=[clock.sourceOriginSeconds,clock.scale,clock.offsetSeconds, ...
        clock.sourceSpanSeconds,clock.maximumExtrapolationSeconds];
    assert(numel(values)==5 && all(isfinite(values)) && clock.scale>0 && ...
        clock.sourceSpanSeconds>0 && clock.maximumExtrapolationSeconds>=0, ...
        'VehicleLocalization:InvalidReceiverClock','Invalid clock coefficients.');
    relative=stamp-clock.sourceOriginSeconds;
    assert(all(isfinite(relative),'all') && ...
        all(relative>=-clock.maximumExtrapolationSeconds,'all') && ...
        all(relative<=clock.sourceSpanSeconds+clock.maximumExtrapolationSeconds,'all'), ...
        'VehicleLocalization:ClockCoverage','Timestamp exceeds the declared clock segment.');
    time=clock.scale*relative+clock.offsetSeconds;
end
