function pose=validateDowntownInitialPose(packet,firstFrameIndex,firstNativeTime)
% validateDowntownInitialPose Bind a single bootstrap packet to the query clock.
    required={'schemaVersion','mode','frameIndex','nativeTimeSeconds','poseXYTheta','referencePoseCount'};
    assert(isscalar(packet) && all(isfield(packet,required)) && packet.schemaVersion==1 && ...
        string(packet.mode)=="reference_pose_once" && packet.referencePoseCount==1, ...
        'VehicleLocalization:InitialPosePacket','Supply one explicit reference initialization packet.');
    assert(isscalar(packet.frameIndex) && packet.frameIndex==firstFrameIndex && ...
        isscalar(packet.nativeTimeSeconds) && abs(packet.nativeTimeSeconds-firstNativeTime)<1e-7, ...
        'VehicleLocalization:InitialPoseClock','The initialization packet must belong to the first query.');
    pose=double(packet.poseXYTheta(:).');
    assert(numel(pose)==3 && isreal(pose) && all(isfinite(pose)), ...
        'VehicleLocalization:InitialPosePacket','Require finite map-frame X,Y,yaw.');
    pose(3)=atan2(sin(pose(3)),cos(pose(3)));
end
