function validation=validateFullLocalizationObserver(outputFolder)
% validateFullLocalizationObserver Check recorded replay and regression scope.
    arguments
        outputFolder (1,1) string="output/mncav_coarse_localization/observer"
    end
    setupVehicleLocalization();
    files=["tests/fullLocalizationObserverTest.m","tests/fullObserverContinuousIssTest.m", ...
        "tests/lateralObserverTest.m", ...
        "tests/localizationMotionInputTest.m","tests/mncavVehicleConfigTest.m", ...
        "tests/wheelLongitudinalSpeedTest.m","tests/wheelMotionInputTest.m", ...
        "tests/synchronousLocalizationTest.m","tests/gnssOutputPointTest.m", ...
        "tests/lidarMatchedInjectionTest.m","tests/lidarRegistrationResidualTest.m"];
    results=runtests(cellstr(files));writetable(table(results),fullfile(outputFolder,'tests.csv'));
    assert(all([results.Passed]),'VehicleLocalization:RegressionFailure','Observer regression failed.');
    stored=load(fullfile(outputFolder,'experiment.mat'));
    assertMncavReplayCurrent(stored.report.metadata.inputMetadata.parameters);
    data=stored.data;cfg=stored.cfg;lateral=stored.lateral;r=stored.runs{1}.estimate;
    repeat=runFullLocalizationObserver(data,stored.lateralDesign,cfg,LateralInputs=lateral);
    repeatDifference=max(abs(repeat.z-r.z),[],'all');assert(repeatDifference==0);
    direct=runFullLocalizationObserver(data,struct(),cfg,LateralInputs=lateral);
    entryDifference=max(abs(direct.z-r.z),[],'all');assert(entryDifference==0);
    assert(r.diagnostics.integrationSubsteps==0);
    dt=diff(r.time);v=r.velocity(2:end,:);p=r.position;
    residual=max(abs(diff(p)-dt.*(v+r.diagnostics.positionCorrection(2:end,1:2)+ ...
        r.diagnostics.positionCorrection(2:end,3:4))),[],'all');
    % Absolute UTM coordinates are about 5e6 m; allow their roundoff.
    assert(residual<1e-7,'Reported baseline-plus-LiDAR position increments must hold.');
    data.gnss.position(data.gnss.time>60,:)=100;
    data.lidar.pose(data.lidar.time>60 & data.lidar.valid,:)=100;
    changed=runFullLocalizationObserver(data,stored.lateralDesign,stored.cfg,LateralInputs=lateral);
    prefixDifference=max(abs(changed.z(r.time<=60,:)-r.z(r.time<=60,:)),[],'all');assert(prefixDifference==0);
    rows=cell(0,4);sourceFiles=["config/fullObserverConfig.m","localization/fullObserverSupport.m", ...
        "localization/runFullLocalizationObserver.m","localization/lidarInjectionSupport.m", ...
        "scripts/runMncavFullObserverExperiment.m", ...
        "scripts/validateFullLocalizationObserver.m","tests/fullLocalizationObserverTest.m", ...
        "scripts/prepareWheelMotionInputs.m","scripts/prepareMncavObserverReplay.m", ...
        "scripts/replayMississippiLocalization.m","tests/wheelMotionInputTest.m", ...
        "tests/synchronousLocalizationTest.m", ...
        "tests/gnssOutputPointTest.m","config/mncavFullObserverConfig.m", ...
        "tests/fullObserverContinuousIssTest.m"];
    for file=sourceFiles
        messages=checkcode(char(file),'-config=factory','-id');
        for j=1:numel(messages),rows(end+1,:)={file,messages(j).line,string(messages(j).id),string(messages(j).message)};end %#ok<AGROW>
    end
    analyzer=cell2table(rows,VariableNames={'file','line','id','message'});
    writetable(analyzer,fullfile(outputFolder,'code_analyzer.csv'));
    d=repeat.diagnostics;modeCounts=arrayfun(@(v) nnz(d.mode==v),0:3);
    validation=struct('tests',numel(results),'allTestsPassed',all([results.Passed]), ...
        'repeatMaximumStateDifference',repeatDifference, ...
        'publicEntryMaximumStateDifference',entryDifference, ...
        'integrationCheckScope',"One synchronous discretization of continuous LMI-certified gains", ...
        'implicitPositionEquationMaximumResidual',residual, ...
        'futureMutationPrefixDifference',prefixDifference, ...
        'analyzerFindings',height(analyzer),'modeCountsNoneGnssLidarBoth',modeCounts, ...
        'continuousLmiVerified',d.continuousLmiVerified, ...
        'continuousInformationQualifiedSamples',nnz(d.continuousInformationQualified), ...
        'headingUnavailableSamples',nnz(d.headingMode==0), ...
        'packetCounts',d.packetCounts, ...
        'maximumTrackRate',d.maximumTrackAngleRate,'rateEnvelopeSatisfied',d.rateEnvelopeSatisfied, ...
        'allTheoremHypothesesVerified',false);
    fid=fopen(fullfile(outputFolder,'validation.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
    fprintf(fid,'%s\n',jsonencode(validation,PrettyPrint=true));disp(validation);
end
