function keep=protectMinorityPoleShaft(features,names,cfg)
% protectMinorityPoleShaft Preserve a narrow continuous subset amid clutter.
% Every condition describes point distributions on existing whole pillars.
% A low owner fraction alone is insufficient: tall, isolated, narrow support
% must persist over height with a stable axis and populated height quarters.
    names=string(names);required=["supportHeight","longestHeight","radialRms", ...
        "isolation","ownerSupportFraction","ownerHeight","minimumQuarterCount", ...
        "quarterCenterStep","fraction015"];
    [present,columns]=ismember(required,names);
    assert(all(present),'perception:MinoritySupportSchema','Model must provide the minority-shaft statistics.');
    x=features(:,columns);
    keep=all(isfinite(x),2) & x(:,1)>=cfg.minimumHeight & ...
        x(:,2)>=cfg.minimumContinuousFraction*x(:,1) & ...
        x(:,3)<=cfg.maximumRadialRms & x(:,4)>=cfg.minimumIsolation & ...
        x(:,5)<=cfg.maximumOwnerSupportFraction & x(:,6)>=cfg.minimumOwnerHeight & ...
        x(:,7)>=cfg.minimumQuarterCount & x(:,8)<=cfg.maximumQuarterCenterStep & ...
        x(:,9)>=cfg.minimumCoreFraction;
end
