function keep=recoverSplitPoleShaft(features,names,hypothesisIds,cfg)
% recoverSplitPoleShaft Share shaft evidence only between supported owners.
% A narrow continuous shaft can straddle pillars containing other-height
% clutter. Both owners must independently contribute an extended subset.
% The shared shape test never labels a neighbor without its own support.
    names=string(names);required=["supportHeight","longestHeight","radialRms", ...
        "isolation","minimumQuarterCount","fraction015","quarterCenterStep", ...
        "maximumGap","aspect","tilt","ownerCount","ownerHeight", ...
        "ownerFraction","ownerSupportFraction","ownerTotalHeight","axisOwnerDistance"];
    [present,columns]=ismember(required,names);
    assert(all(present),'perception:SplitSupportSchema','Model must provide split-shaft statistics.');
    x=features(:,columns);keep=false(size(x,1),1);if isempty(x),return;end
    finite=all(isfinite(x),2);
    shaft=finite & x(:,1)>=cfg.minimumHeight & ...
        x(:,2)>=cfg.minimumContinuousFraction*x(:,1) & ...
        x(:,3)<=cfg.maximumRadialRms & x(:,4)>=cfg.minimumIsolation & ...
        x(:,5)>=cfg.minimumQuarterCount & x(:,6)>=cfg.minimumCoreFraction & ...
        x(:,7)<=cfg.maximumQuarterCenterStep & x(:,8)<=cfg.maximumGap & ...
        x(:,9)<=cfg.maximumAspect & x(:,10)<=cfg.maximumTilt;
    owner=finite & x(:,11)>=cfg.minimumOwnerCount & x(:,12)>=cfg.minimumOwnerHeight & ...
        x(:,13)>=cfg.minimumOwnerFraction & x(:,14)>=cfg.minimumOwnerSupportFraction & ...
        x(:,14)<=cfg.maximumOwnerSupportFraction & ...
        x(:,12)<=cfg.maximumOwnerHeightFraction*x(:,15) & x(:,16)<=cfg.maximumAxisOwnerDistance;
    % Feature extraction emits exactly one row per owner per hypothesis.
    [~,~,group]=unique(hypothesisIds);count=accumarray(group,double(owner & shaft));
    keep=owner & shaft & count(group)>=cfg.minimumOwners;
end
