function signature=mncavVdbInputSignature(datasetFolder,interfaceFile)
% mncavVdbInputSignature Reject sensor caches from changed data or models.
    root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
    files=[string(fullfile(datasetFolder,'sensors.csv')),string(interfaceFile), ...
        string(fullfile(root,'config',{'mncavVehicleParameters.json','mncavMotionOutputPoint.json', ...
        'mncavVdbConfig.m','mncavSensorParameters.json','lateralObserverConfig.m','wheelSpeedObserverConfig.m'})), ...
        string(fullfile(root,'scripts','carla','prepareMncavVdbInputs.m')), ...
        string(fullfile(root,'localization','estimateWheelLongitudinalSpeed.m')), ...
        string(fullfile(root,'localization','lateralObserver', ...
        {'runLateralVelocityObserver.m','designLateralObserverGains.m'}))];
    digest=java.security.MessageDigest.getInstance('SHA-256');
    for file=files,digest.update(uint8(fileread(file)));digest.update(uint8(0));end
    signature=string(lower(reshape(dec2hex(typecast(digest.digest(),'uint8'),2).',1,[])));
end
