function auditFrame900()
% auditFrame900: Localize a user-confirmed pole absent from frozen fine labels.
% The review labels pillar occupancy only, not every point inside that pillar.
    root=setupVehicleLocalization();folder=fileparts(mfilename('fullpath'));
    addpath(fullfile(root,'research','pillar_fine_alignment_20260926'));
    frame=loadPointCloudFrame(fullfile(root,'data','raw','MissisipiPointClouds.mat'),900);
    referenceFile=fullfile(root,'output','pole_precision_20260927','mississippi.mat');
    frozen=load(referenceFile,'frames','references');at=find(frozen.frames==900,1);
    assert(~isempty(at),'Frame 900 must have a frozen fine reference.');
    reference=frozen.references{at};fine=double(reference.pointIndices(:));
    xyz=double([frame.x(:),frame.y(:),frame.z(:)]);
    assert(isequal(xyz(fine,:),double(reference.points)),'Frozen reference/source mismatch.');
    p=perceiveFrame(frame,perceptionConfig('Mississippi'));g=p.candidates.geometry;
    selected=double(p.candidates.pillarIndices{p.candidates.semanticNames=="pole"}(:));
    assert(isequal(selected,5744),'The review applies to the unique displayed pillar 5744.');
    [alignment,detail]=measureFinePoleAlignment(frame,fine,selected,g);
    assert(alignment.extraPillarCount==1 && alignment.coveredFinePointCount==0);
    dims=double(g.mapSize);spacing=double(g.cellSize);origin=double(g.origin);
    [row,col]=ind2sub(dims,selected);lower=origin+([col row]-1).*spacing;upper=lower+spacing;
    bins=floor((xyz(:,1:2)-origin)./spacing)+1;
    valid=all(isfinite(xyz),2) & all(bins>=1 & bins<=[dims(2),dims(1)],2);
    ids=zeros(size(xyz,1),1);ids(valid)=sub2ind(dims,bins(valid,2),bins(valid,1));
    source=find(ids==selected);points=xyz(source,:);center=lower+spacing/2;
    distance=sqrt(sum((xyz(fine,1:2)-center).^2,2));
    result=struct('dataset',"Mississippi",'frame',900,'pillarId',selected, ...
        'geometry',g,'xyLowerInclusive',lower,'xyUpperExclusive',upper,'xyCenter',center, ...
        'sourcePointsInPillar',numel(source),'sourceZRange',[min(points(:,3)),max(points(:,3))], ...
        'fineReferencePointsInPillar',nnz(ismember(fine,source)), ...
        'nearestFineReferenceXYDistanceToCenter',min(distance), ...
        'fineReferencePillarIds',detail.finePillarIds,'originalReferenceAlignment',alignment, ...
        'sourcePointIndicesInPillar',source, ...
        'referenceCache',"output/pole_precision_20260927/mississippi.mat", ...
        'rawSource',"data/raw/MissisipiPointClouds.mat", ...
        'review',struct('source',"User inspection of the displayed frame-900 comparison", ...
            'assertion',"The detected coarse pole is real and absent from the fine reference", ...
            'scope',"The selected pillar contains at least some real pole points", ...
            'pillarContainsPole',true,'pointLevelLabelsProvided',false, ...
            'generalization',"One reviewed pillar only; no sequence-wide physical accuracy estimate"));
    file=fopen(fullfile(folder,'frame900_audit.json'),'w');cleanup=onCleanup(@()fclose(file));
    fprintf(file,'%s\n',jsonencode(result,PrettyPrint=true));
    disp(rmfield(result,{'sourcePointIndicesInPillar','review'}));
end
