function checkFinalImplementation()
% checkFinalImplementation Check deployed geometry, registration and window contracts.
    root=setupVehicleLocalization();addpath(root);dest=fileparts(mfilename('fullpath'));
    previous=getenv('VEHICLE_LOCALIZATION_DATA_ROOT');restore=onCleanup(@()setenv('VEHICLE_LOCALIZATION_DATA_ROOT',previous)); %#ok<NASGU>
    setenv('VEHICLE_LOCALIZATION_DATA_ROOT',fullfile(root,'data'));
    files=["canonicalPyramidTest","geometricRegistrationTest","distributionRegistrationTest", ...
        "repeatabilityRegistrationTest","lineDirectionRegistrationTest","positionAidedRegistrationTest", ...
        "registrationInformationTest","relativeHeightAssociationTest","localizationSourceWindowTest", ...
        "softPointAssociationTest","robustPoseGraphTest","curbSurfaceGeometryTest","scanDeskewTest", ...
        "wholePillarPerceptionTest","coarseSemanticProbabilityCloudTest","perceptionFeatureSelectionTest", ...
        "pillarPoleDistributionTest","pillarPoleValidationTest"];
    suite=testsuite(fullfile(root,'tests',files(1)+".m"));
    for f=files(2:end),suite=[suite,testsuite(fullfile(root,'tests',f+".m"))];end %#ok<AGROW>
    result=run(suite);report=table(string({result.Name}).',[result.Passed].',[result.Failed].',[result.Incomplete].', ...
        VariableNames={'test','passed','failed','incomplete'});writetable(report,fullfile(dest,'final_tests.csv'));assert(all(report.passed));
    checked=["config/curbBoundaryGeometryConfig.m","config/perceptionConfig.m","perception/perceiveFrame.m", ...
        "perception/groundFeatures/estimateCurbBoundaryGeometry.m","perception/semanticProduct/applyCurbBoundaryScatter.m", ...
        "perception/offGroundFeatures/classifyPillarPoleSupport.m","localization/updateRobustPoseGraph.m", ...
        "tests/curbSurfaceGeometryTest.m","tests/scanDeskewTest.m","tests/robustPoseGraphTest.m", ...
        "research/root_cause_matching_20260929/deskewStoredFrame.m"];
    counts=zeros(numel(checked),1);
    for k=1:numel(checked)
        findings=checkcode(fullfile(root,checked(k)),'-config=factory');counts(k)=numel(findings);
        if ~isempty(findings),disp(checked(k));disp(struct2table(findings));end
    end
    writetable(table(checked.',counts,VariableNames={'file','findings'}),fullfile(dest,'code_analysis.csv'));assert(~any(counts));
    fprintf('FINAL IMPLEMENTATION: %d tests passed; %d files clean.\n',height(report),numel(checked));
end
