function calibration = validateLidarFrameCalibration(calibration)
% validateLidarFrameCalibration: Validate a rigid stored-frame-to-body increment.
    assert(isstruct(calibration) && isscalar(calibration) && ...
        all(isfield(calibration,{'rotation','translation','identifier'})), ...
        'VehicleLocalization:InvalidCalibration','Incomplete frame calibration.');
    r=double(calibration.rotation); t=double(calibration.translation(:).');
    assert(isequal(size(r),[3 3]) && isreal(r) && all(isfinite(r),'all') && ...
        norm(r*r.'-eye(3),'fro')<1e-8 && det(r)>0 && ...
        numel(t)==3 && isreal(t) && all(isfinite(t)) && ...
        isscalar(string(calibration.identifier)) && strlength(string(calibration.identifier))>0, ...
        'VehicleLocalization:InvalidCalibration','Expected a proper rotation, finite XYZ translation and identifier.');
    calibration.rotation=r; calibration.translation=t;
    calibration.identifier=string(calibration.identifier);
end
