function voxelGrid = voxelizePillars(pillars, dz, zReference)
% voxelizePillars: Split whole XY pillars into fixed height layers for offline fine detection.
% Height boundaries are zReference + k*dz. The caller supplies the reference
% from common preprocessing so dropping ground returns cannot change the
% histogram phase. XY membership is taken from the pillars as is.
% No dense statistics or inverse voxel lookup is allocated.
    assert(isstruct(pillars) && all(isfield(pillars, ["gridConfig", "points", "pointIndices", ...
        "pointPillarSub", "pointAttributes"])), "voxelizePillars requires pillarizePointCloud output.");
    dz = double(dz);
    assert(isscalar(dz) && isfinite(dz) && dz > 0, "perception:InvalidLayerHeight", ...
        "Height layers require one positive finite spacing.");
    xy = pillars.gridConfig;
    z = double(pillars.points(:, 3));
    zFloor = double(zReference);
    assert(isscalar(zFloor) && isfinite(zFloor) && all(z >= zFloor), ...
        "perception:InvalidHeightReference", ...
        "The height reference must be finite and no higher than any retained return.");
    zBin = floor((z - zFloor)./dz) + 1;
    dims = [double(xy.dims(1:2)), max([zBin; 1])];
    voxelSize = [double(xy.voxelSize(1:2)), dz];
    minCorner = [double(xy.minCorner(1:2)), zFloor];
    pointVoxelSub = [double(pillars.pointPillarSub), zBin];
    voxelGrid = struct("spatialIndexType", "voxelGrid", ...
        "gridConfig", struct("dims", dims, "voxelSize", voxelSize, "minCorner", minCorner, ...
        "maxCorner", minCorner + dims.*voxelSize, "origin", minCorner + voxelSize./2), ...
        "points", pillars.points, "pointIndices", pillars.pointIndices, ...
        "pointVoxelSub", int32(pointVoxelSub), ...
        "pointVoxelLinIdx", int32(sub2ind(dims, pointVoxelSub(:, 1), pointVoxelSub(:, 2), pointVoxelSub(:, 3))), ...
        "pointAttributes", pillars.pointAttributes, "numFilteredPoints", size(pillars.points, 1));
end
